server:
  port: 31450
spring:
  application:
    name: manage-media-processor
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: mc_media
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
manage-media:
  video-location: D:/Sources/video/
  ffmpeg-path: D:/Program Files/ffmpeg/bin/ffmpeg.exe
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video